### ISSUE TITLE
Help with webpack2  postcss.config.js

### ISSUE THREAD

**Issue by anoopd** [tailwindcss/webpack-starter#1]
Can somebody please help with how to configure tailwind with webpack ,  can somebody let me know how to pass the config file path ?

     module.exports = {
     plugins: {
     'postcss-import': {},
       'tailwindcss': {  /* how to pass path to config file */ },
     'postcss-cssnext': {
      browsers: ['last 2 versions', '> 5%'],
    },
      'autoprefixer': {},
    },
    };

**Comment by adamwathan** [comment]
Make `plugins` an array instead of an object and pass the actual plugins through instead of just the names, like we do in the provided example config:

https://github.com/tailwindcss/webpack-starter/blob/master/postcss.config.js

**Comment by anoopd** [comment]
Hi Adam ,
                    Thank you so much for the reply  ........  i already have the project working with the array thing , i was just curious about using the  object notation thus avoiding the 'require '  , and thanks for letting me know that CSSNext include autoprefixer . Will go back to array config and yes you certainly can close this .
