### ISSUE TITLE
TypeError: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by cwgabel** [tailwindcss/webpack-starter#20]
describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^
TypeError: Cannot read property 'properties' of undefined

[google search gives this as a fix...](https://github.com/plotly/dash-component-boilerplate/issues/12)

which calls for an updated package.json. 
```
 "webpack": "^4.20.2",
 "webpack-cli": "^3.1.1",
```

fixed the problem for me on windows 8, node 10.12

**Comment by rliessum** [comment]
I did encounter this issue and was raising an issue for it but noticed this existing issue.
Maybe just to a pull request on package.json instead with the fixed versions?
