### ISSUE TITLE
having trouble running dev server

### ISSUE THREAD

**Issue by justinchristensen66** [tailwindcss/webpack-starter#25]
I installed and ran npm run dev but got TypeError: Cannot read property 'properties' of undefined.
I was running node 8.9.1 through nvm. Full message read 
 npm run dev

> @ dev /Users/justinchristensen/Sandbox/Try-Out-Projects/Tailwind/Proj-One/webpack-starter
> cross-env NODE_ENV=development webpack-dev-server

/Users/justinchristensen/Sandbox/Try-Out-Projects/Tailwind/Proj-One/webpack-starter/node_modules/webpack-cli/bin/config-yargs.js:89
				describe: optionsSchema.definitions.output.properties.path.description,
				                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/Users/justinchristensen/Sandbox/Try-Out-Projects/Tailwind/Proj-One/webpack-starter/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at Object.<anonymous> (/Users/justinchristensen/Sandbox/Try-Out-Projects/Tailwind/Proj-One/webpack-starter/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `cross-env NODE_ENV=development webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Sorry if this dumb question, I just really wanted to get started with Tailwind.

**Comment by neoighodaro** [comment]
@justinchristensen66 it's not a dumb question. I am also having the same issue. I know it has something to do with using `webpack-cli` v3 instead of 2. However doing just that removed the errors but the compile is not working.

**Comment by Kalaneee** [comment]
I have the same issue.

**Comment by jessebraham** [comment]
Just as another data point, same issue.

**OS:** Windows 10 Pro 1803
**node:** `v10.11.0`
**npm:** `v6.5.0`

**Comment by jessebraham** [comment]
So #22 fixes this, been open for almost a month. Updating `webpack` to `^4.27.1` and `webpack-cli` to `^3.1.2` in your `package.json` file will fix the error.

**Comment by DiegoArrieta** [comment]
thanks @jessebraham

**Comment by justinchristensen66** [comment]
thanks @jessebraham that fixes it!
